[DATA]
dataset = "https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv"

[MODEL]
random_forest_path = "model/saved/random_forest.pkl"
decision_tree_path = "model/saved/decision_tree.pkl"
svm_path = "model/saved/svm.pkl"